name: MATLAB Build
on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
  build-windows:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
  build-macos:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
