name: MATLAB Build
on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: matlab-actions/run-build@v2
        with:
          tasks: release
  build-windows:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: matlab-actions/run-build@v2
        with:
          tasks: release
  build-macos:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build MATLAB toolbox
        uses: matlab-actions/run-build@v2
        with:
          tasks: release
