name: MATLAB Build
on: 
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Check Env
        run: echo $MATLAB_ROOT
      - name: Check Env
        run: env
