name: MATLAB Build
on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Restore buildtool cache
        id: build-cache-linux
        uses: actions/cache@v4
        with:
          key: build-cache-linux
          path: |
            .buildtool
            toolbox
            release
            results
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
  build-windows:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Restore buildtool cache
        id: build-cache-windows
        uses: actions/cache@v4
        with:
          key: build-cache-windows
          path: |
            .buildtool
            toolbox
            release
            results
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
  build-macos:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Restore buildtool cache
        id: build-cache-macos
        uses: actions/cache@v4
        with:
          key: build-cache-macos
          path: |
            .buildtool
            toolbox
            release
            results
      - name: Build MATLAB toolbox
        uses: davidbuzinski/run-command@main
        with:
          command: buildtool release
