name: Build and Test
on: [push]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - run: echo $MW_CI
      - run: echo $MATHWORKS_LICENSING_ENDPOINT
      - name: Run command
        uses: davidbuzinski/run-command@main
        with:
          command: ver
  job2:
    runs-on: self-hosted
    steps:
      - run: echo $MW_CI
      - run: echo $MATHWORKS_LICENSING_ENDPOINT
      - name: Run command
        uses: davidbuzinski/run-command@main
        with:
          command: ver
  job3:
    runs-on: self-hosted
    steps:
      - run: echo $MW_CI
      - run: echo $MATHWORKS_LICENSING_ENDPOINT
      - name: Run command
        uses: davidbuzinski/run-command@main
        with:
          command: ver
