name: MATLAB Build
on: 
  push:

env:
  MATHWORKS_LICENSING_ENDPOINT: dev
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run Command
        run: matlab -batch 'ver'
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run Command
        run: matlab -batch 'ver'
